# Setup
title: Notes
description: on knowledge managment, databases, and networks 
tagline: 
url: 
paginate: 1
baseurl: "https://adampuchejda.github.io/"
permalink: pretty
githubpage: "https://github.com/adampuchejda"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Adam Puchejda
  url: https://twitter.com/adampuchejda
  email: adam.puchejda@protonmail.com

# Custom vars
version: 0.2.0
